import type{Catalog,CatalogMaterial,CatalogNode,TocItem}from"@/lib/types";
export const REPO_OWNER="GanzSchool",REPO_NAME="Materials",REPO_BRANCH="main",CONTENT_ROOT="materials-platform/content";
export const RAW_CONTENT_BASE=`https://raw.githubusercontent.com/${REPO_OWNER}/${REPO_NAME}/${REPO_BRANCH}/${CONTENT_ROOT}`;
export const fallbackCatalog:Catalog={version:1,title:"Ganz Tananyag",nodes:[{type:"category",id:"database",title:"Adatbázis-kezelés",slug:"adatbazis",order:1,children:[{type:"category",id:"sql",title:"SQL",slug:"sql",order:1,children:[{type:"material",id:"sql-alaplekerdezesek",title:"Alaplekérdezések",slug:"alaplekerdezesek",description:"SELECT, WHERE és ORDER BY rendezett ismétlése.",contentPath:"sql/alaplekerdezesek.mdx",order:1,published:true},{type:"material",id:"sql-group-by",title:"GROUP BY és HAVING",slug:"group-by-having",description:"Csoportosítás, aggregálás és csoportfeltételek.",contentPath:"sql/group-by-having.mdx",order:2,published:true}]}]},{type:"category",id:"frontend",title:"Frontend programozás",slug:"frontend",order:2,children:[{type:"category",id:"javascript",title:"JavaScript",slug:"javascript",order:1,children:[]},{type:"category",id:"nextjs",title:"Next.js",slug:"nextjs",order:2,children:[]}]}]};
export async function getCatalog():Promise<Catalog>{try{const r=await fetch(`${RAW_CONTENT_BASE}/catalog.json`,{cache:"no-store"});if(!r.ok)return fallbackCatalog;return await r.json() as Catalog}catch{return fallbackCatalog}}
export async function getMaterialSource(material:CatalogMaterial):Promise<string>{try{const r=await fetch(`${RAW_CONTENT_BASE}/${material.contentPath}`,{cache:"no-store"});if(!r.ok)throw new Error();return await r.text()}catch{return material.id==="sql-group-by"?FALLBACK_GROUP_BY:FALLBACK_BASICS}}
export function findMaterialBySlug(catalog:Catalog,slug:string[]):CatalogMaterial|null{const wanted=slug.join("/");const walk=(nodes:CatalogNode[],parents:string[]):CatalogMaterial|null=>{for(const node of nodes){if(node.type==="category"){const f=walk(node.children,[...parents,node.slug]);if(f)return f}else if([...parents,node.slug].join("/")===wanted&&node.published)return node}return null};return walk(catalog.nodes,[])}
export function extractToc(source:string):TocItem[]{return source.split("\n").map(line=>{const m=line.match(/^(##|###)\s+(.+)$/);if(!m)return null;const title=m[2].replace(/[`*_]/g,"").trim();return{id:slugify(title),title,level:m[1]==="##"?2:3}as TocItem}).filter(Boolean)as TocItem[]}
export function slugify(v:string){return v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"")||"tananyag"}
const FALLBACK_BASICS=`---\ntitle: Alaplekérdezések\n---\n# Alaplekérdezések\n\nAz SQL-lekérdezések alapjai: mit kérünk le, mely sorok maradnak, és milyen sorrendben jelenjenek meg.\n\n<Info title="Órai cél">A fejezet végére önállóan tudsz oszlopokat kiválasztani, rekordokat szűrni és az eredményt rendezni.</Info>\n\n## SELECT – mit szeretnél látni?\n\nA SELECT határozza meg, mely oszlopok jelenjenek meg.\n\n~~~sql\nSELECT nev, ar\nFROM termekek;\n~~~\n\n## WHERE – mely sorok maradjanak?\n\nA WHERE feltétel a sorokat szűri.\n\n<Task number="1.1" title="Első szűrés">Listázd a 10 000 Ft-nál drágább termékek nevét és árát.</Task>\n\n## ORDER BY – milyen sorrendben?\n\nAz ORDER BY az eredmény sorrendjét állítja be.`;
const FALLBACK_GROUP_BY=`---\ntitle: GROUP BY és HAVING\n---\n# GROUP BY és HAVING\n\nAmikor csoportokra vagy kíváncsi, a GROUP BY az egyik legfontosabb eszközöd.\n\n## Mi történik csoportosításkor?\n\nA GROUP BY az azonos értékű rekordokat egy csoportba rendezi.\n\n<SQLExample title="Dolgozók száma osztályonként" query={\`SELECT osztaly, COUNT(*) AS letszam\\nFROM dolgozok\\nGROUP BY osztaly;\`} />\n\n## HAVING – feltétel a csoportokra\n\nA WHERE a csoportosítás előtt, a HAVING utána szűr.\n\n<Info title="Vizsgatipp">Aggregált értékre adott feltételnél jellemzően HAVING kell.</Info>`;
