import{NextRequest,NextResponse}from"next/server";
import{CONTENT_ROOT,REPO_BRANCH,REPO_NAME,REPO_OWNER,slugify}from"@/lib/catalog";
import type{Catalog,CatalogCategory,CatalogNode}from"@/lib/types";
const api="https://api.github.com";
type Body={action:"upsertMaterial"|"createCategory";token?:string;parentId?:string|null;title:string;slug?:string;description?:string;content?:string};
async function gh(token:string,path:string,init?:RequestInit){const r=await fetch(`${api}${path}`,{...init,headers:{accept:"application/vnd.github+json",authorization:`Bearer ${token}`,"x-github-api-version":"2022-11-28","content-type":"application/json",...(init?.headers||{})},cache:"no-store"});if(!r.ok){const m=await r.text();throw new Error(`GitHub API ${r.status}: ${m.slice(0,220)}`)}return r.json()}
async function loadCatalog(token:string):Promise<Catalog>{const f=await gh(token,`/repos/${REPO_OWNER}/${REPO_NAME}/contents/${CONTENT_ROOT}/catalog.json?ref=${REPO_BRANCH}`);return JSON.parse(Buffer.from(f.content,"base64").toString("utf8"))as Catalog}
function findCategory(nodes:CatalogNode[],id?:string|null):CatalogCategory|null{if(!id)return null;for(const n of nodes)if(n.type==="category"){if(n.id===id)return n;const f=findCategory(n.children,id);if(f)return f}return null}
async function atomicCommit(token:string,files:{path:string;content:string}[],message:string){const ref=await gh(token,`/repos/${REPO_OWNER}/${REPO_NAME}/git/ref/heads/${REPO_BRANCH}`),parentSha=ref.object.sha as string,parent=await gh(token,`/repos/${REPO_OWNER}/${REPO_NAME}/git/commits/${parentSha}`);const entries:{path:string;mode:string;type:string;sha:string}[]=[];for(const f of files){const b=await gh(token,`/repos/${REPO_OWNER}/${REPO_NAME}/git/blobs`,{method:"POST",body:JSON.stringify({content:f.content,encoding:"utf-8"})});entries.push({path:f.path,mode:"100644",type:"blob",sha:b.sha})}const tree=await gh(token,`/repos/${REPO_OWNER}/${REPO_NAME}/git/trees`,{method:"POST",body:JSON.stringify({base_tree:parent.tree.sha,tree:entries})}),commit=await gh(token,`/repos/${REPO_OWNER}/${REPO_NAME}/git/commits`,{method:"POST",body:JSON.stringify({message,tree:tree.sha,parents:[parentSha]})});await gh(token,`/repos/${REPO_OWNER}/${REPO_NAME}/git/refs/heads/${REPO_BRANCH}`,{method:"PATCH",body:JSON.stringify({sha:commit.sha,force:false})});return commit.sha as string}
export async function POST(req:NextRequest){try{const b=await req.json()as Body,token=b.token?.trim()||process.env.GITHUB_TOKEN?.trim();if(!token)return NextResponse.json({error:"A publikáláshoz GitHub token szükséges. Add meg az admin felületen, vagy állíts be GITHUB_TOKEN környezeti változót."},{status:401});if(!b.title?.trim())return NextResponse.json({error:"A cím kötelező."},{status:400});const catalog=await loadCatalog(token);if(b.action==="createCategory"){const parent=findCategory(catalog.nodes,b.parentId),siblings=parent?parent.children:catalog.nodes,cat:CatalogCategory={type:"category",id:`cat-${Date.now().toString(36)}`,title:b.title.trim(),slug:slugify(b.slug||b.title),order:siblings.length+1,children:[]};siblings.push(cat);catalog.version+=1;const commitSha=await atomicCommit(token,[{path:`${CONTENT_ROOT}/catalog.json`,content:JSON.stringify(catalog,null,2)+"\n"}],`content: add ${cat.title} category`);return NextResponse.json({ok:true,commitSha,catalog})}if(!b.content?.trim())return NextResponse.json({error:"Az MDX tartalom üres."},{status:400});const parent=findCategory(catalog.nodes,b.parentId);if(!parent)return NextResponse.json({error:"Válassz ki egy cél menüpontot a tartalomfában."},{status:400});const materialSlug=slugify(b.slug||b.title),filePath=`${slugify(parent.slug)}/${materialSlug}.mdx`,existing=parent.children.find(n=>n.type==="material"&&n.slug===materialSlug);if(existing&&existing.type==="material"){existing.title=b.title.trim();existing.description=b.description?.trim();existing.contentPath=filePath;existing.published=true}else parent.children.push({type:"material",id:`mat-${Date.now().toString(36)}`,title:b.title.trim(),slug:materialSlug,description:b.description?.trim(),contentPath:filePath,order:parent.children.length+1,published:true});catalog.version+=1;const commitSha=await atomicCommit(token,[{path:`${CONTENT_ROOT}/${filePath}`,content:b.content.trimEnd()+"\n"},{path:`${CONTENT_ROOT}/catalog.json`,content:JSON.stringify(catalog,null,2)+"\n"}],`content: publish ${b.title.trim()}`);return NextResponse.json({ok:true,commitSha,catalog})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Ismeretlen publikálási hiba."},{status:500})}}
