/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mySidebar: [
    {
      type: 'autogenerated',
      dirName: 'Webprogramozás', // Automatikusan generálja a sidebar-t a Webprogramozás mappa alapján
    },
  ],
};

module.exports = sidebars;
