/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mySidebar: [
    {
      type: 'autogenerated',
      dirName: 'Webprogramozás', // Automatikusan generálja a sidebar-t a 'docs/Webprogramozás' mappa alapján

    },
    // Egyéb sidebar elemek itt hozzáadhatók, ha szükséges
  ],
};

module.exports = sidebars;

